In [0]:
import pickle
with open('train.pkl', 'rb') as f:
    data = pickle.load(f)

In [0]:
import pickle
with open('test.pkl', 'rb') as f:
    data1= pickle.load(f)

In [0]:
data

Id  ...  y
0          0  ...  1
1          1  ...  0
2          2  ...  0
3          3  ...  0
4          4  ...  0
...      ...  ... ..
84995  84995  ...  0
84996  84996  ...  0
84997  84997  ...  0
84998  84998  ...  0
84999  84999  ...  0

[85000 rows x 4 columns]

In [0]:
Train_data=data['X']=data['c']+ " " +data['r']

In [0]:
data1

Id  ...                                                  r
0          0  ...                                      Răchëd MhāmDī
1          1  ...                         انا.منحبش.مسي.انحب.رونالدو
2          2  ...                                  الmarketing like 
3          3  ...                 اخيب حاجة عملتها حياتي شريت اوريدو
4          4  ...                                    troudouha moch 
...      ...  ...                                                ...
37585  37585  ...                           doubles puces puce wahda
37586  37586  ...                            بربي اكثر معلومات offre
37587  37587  ...   Bonjour Pour consulter votre numéro Mobile co...
37588  37588  ...   kont nsob ya3twni merci tnahatli kifech na3me...
37589  37589  ...                                               فهمت

[37590 rows x 3 columns]

In [0]:
I=data1.loc[:,'Id']

In [0]:
I

0            0
1            1
2            2
3            3
4            4
         ...  
37585    37585
37586    37586
37587    37587
37588    37588
37589    37589
Name: Id, Length: 37590, dtype: int64

In [0]:
test_data=data1['c']+data1['r']

In [0]:
test_data

0         _t_ Yrem _t_  _t_ lords نسيطرو عليهم الغروبات...
1         _t_ Yrem _t_  _t_ lords نسيطرو عليهم الغروبات...
2         _t_ Yrem _t_  _t_ lords نسيطرو عليهم الغروبات...
3         _t_ Yrem _t_  _t_ lords نسيطرو عليهم الغروبات...
4         _t_ Yrem _t_  _t_ lords نسيطرو عليهم الغروبات...
                               ...                        
37585                        _t_  doubles puces puce wahda
37586                         _t_  بربي اكثر معلومات offre
37587     _t_  Bonjour Pour consulter votre numéro Mobi...
37588     _t_  kont nsob ya3twni merci tnahatli kifech ...
37589                                            _t_  فهمت
Length: 37590, dtype: object

In [0]:
data['X'][0]

' _t_ comment faire pour choisir bonne musique pour samma3ni _t_ Bonsoir Rimo simple consultez catalogue toutes tonalités Samma3ni lien suivant: https://samma3ni.ooredoo.tn/oortn/front/# /web/home votre service Lotfi Community Manager _t_ Merci peux donner musique numero _t_ vous cherchez titre bien déterminé Lotfi Community Manager _t_ connais jara _t_ Vous pouvez faire recherche avec titre composant *150*4#. Lotfi Community Manager _t_ Vous dites suspendu solde _t_ Dans vous devez recharger votre compte pour vous piussez acheter tonalité. votre service Lotfi Community Manager merci'

In [0]:
import pickle
with open('test.pkl', 'rb') as f:
    data1 = pickle.load(f)

In [0]:
D=data['c'].tolist()

In [0]:
import numpy as np
train_label=np.array(data['y'])

In [0]:
train_label

array([1, 0, 0, ..., 0, 0, 0])

In [0]:
T=data['r'].tolist()

In [0]:
D=D+T

In [0]:
D

[' _t_ comment faire pour choisir bonne musique pour samma3ni _t_ Bonsoir Rimo simple consultez catalogue toutes tonalités Samma3ni lien suivant: https://samma3ni.ooredoo.tn/oortn/front/# /web/home votre service Lotfi Community Manager _t_ Merci peux donner musique numero _t_ vous cherchez titre bien déterminé Lotfi Community Manager _t_ connais jara _t_ Vous pouvez faire recherche avec titre composant *150*4#. Lotfi Community Manager _t_ Vous dites suspendu solde _t_ Dans vous devez recharger votre compte pour vous piussez acheter tonalité. votre service Lotfi Community Manager',
 ' _t_ comment faire pour choisir bonne musique pour samma3ni _t_ Bonsoir Rimo simple consultez catalogue toutes tonalités Samma3ni lien suivant: https://samma3ni.ooredoo.tn/oortn/front/# /web/home votre service Lotfi Community Manager _t_ Merci peux donner musique numero _t_ vous cherchez titre bien déterminé Lotfi Community Manager _t_ connais jara _t_ Vous pouvez faire recherche avec titre composant *150*4

In [0]:
data1

Id  ...                                                  r
0          0  ...                                      Răchëd MhāmDī
1          1  ...                         انا.منحبش.مسي.انحب.رونالدو
2          2  ...                                  الmarketing like 
3          3  ...                 اخيب حاجة عملتها حياتي شريت اوريدو
4          4  ...                                    troudouha moch 
...      ...  ...                                                ...
37585  37585  ...                           doubles puces puce wahda
37586  37586  ...                            بربي اكثر معلومات offre
37587  37587  ...   Bonjour Pour consulter votre numéro Mobile co...
37588  37588  ...   kont nsob ya3twni merci tnahatli kifech na3me...
37589  37589  ...                                               فهمت

[37590 rows x 3 columns]

In [0]:
vocab_size = len(D)
print(vocab_size)

170000


In [0]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
import nltk
import string

Using TensorFlow backend.


In [0]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(Train_data)
sequences = tokenizer.texts_to_sequences(Train_data)
train_dataset = pad_sequences(sequences, maxlen=70,padding='post')

In [0]:
train_dataset

array([[  284,    72,   172, ...,     3,     4,     8],
       [   72,   172,   633, ...,     4,  3955,  3429],
       [   72,   172,   633, ...,     4, 26223, 26224],
       ...,
       [    1, 21282,  5920, ...,     0,     0,     0],
       [    1, 21282,  5920, ...,     0,     0,     0],
       [    4,     1,  7463, ...,    15,     3,     4]], dtype=int32)

In [0]:
train_dataset.shape

(85000, 70)

In [0]:
test_data1=data1['c']+data1['r']
sequences = tokenizer.texts_to_sequences(test_data1)
test_Data = pad_sequences(sequences, maxlen=70,padding='post')

In [0]:
test_Data

array([[    1, 22499,     1, ...,     0,     0,     0],
       [    1, 22499,     1, ...,     0,     0,     0],
       [    1, 22499,     1, ...,     0,     0,     0],
       ...,
       [    1,    20,     9, ...,     0,     0,     0],
       [    1,   721,   115, ...,     0,     0,     0],
       [    1,  1879,     0, ...,     0,     0,     0]], dtype=int32)

In [0]:
sequences

[[1, 22499, 1, 1, 23496, 23497, 1088, 23498, 359, 19873, 19874],
 [1, 22499, 1, 1, 23496, 23497, 1088, 23498, 359, 1803, 4204, 6974, 463, 7126],
 [1, 22499, 1, 1, 23496, 23497, 1088, 23498, 359, 5252, 1710],
 [1,
  22499,
  1,
  1,
  23496,
  23497,
  1088,
  23498,
  359,
  7388,
  205,
  3167,
  1070,
  761,
  48],
 [1, 22499, 1, 1, 23496, 23497, 1088, 23498, 359, 14475, 668],
 [1, 22499, 1, 1, 23496, 23497, 1088, 23498, 359, 19168, 23],
 [1,
  22499,
  1,
  1,
  23496,
  23497,
  1088,
  23498,
  359,
  3577,
  2034,
  495,
  3629,
  2617,
  5019,
  7736,
  7737],
 [1,
  22499,
  1,
  1,
  23496,
  23497,
  1088,
  23498,
  359,
  728,
  536,
  593,
  33,
  5924,
  5957,
  160,
  22,
  536,
  52],
 [1, 22499, 1, 1, 23496, 23497, 1088, 23498, 359, 603, 7453, 568],
 [1,
  22499,
  1,
  1,
  23496,
  23497,
  1088,
  23498,
  359,
  25997,
  1245,
  143,
  30010,
  30011,
  3785,
  327,
  620,
  21808,
  21808,
  30012,
  30013,
  5910,
  30014,
  30015],
 [1, 24500],
 [1, 24500, 167, 

In [0]:
t = Tokenizer()
vocab_size=len(tokenizer.word_counts)+1


In [0]:
vocab_size

30939

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow_datasets as tfds
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(30939,70),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5)
    
])


In [0]:
model.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.Adam(1e-3),
              metrics=['accuracy'])


In [0]:
history = model.fit(train_dataset,train_label,epochs=5,validation_split=0.33)


Train on 56949 samples, validate on 28051 samples
Epoch 1/5
56949/56949 [==============================] - 510s 9ms/sample - loss: 0.9472 - acc: 0.8955 - val_loss: 0.3372 - val_acc: 0.9000
Epoch 2/5
 9760/56949 [====>.........................] - ETA: 6:20 - loss: 0.9123 - acc: 0.8992

In [0]:
Prediction= model.predict(test_Data,batch_size=None)


In [0]:
Prediction

array([[0.4957094 ],
       [0.49550503],
       [0.49556446],
       ...,
       [0.49439397],
       [0.49564832],
       [0.49652833]], dtype=float32)

In [0]:
result_test=[]
for i in range(len(Prediction)):
  result_test.append(float(Prediction[i]))


In [0]:
import pandas as pd
import numpy as np
sub=pd.DataFrame(result_test,columns=['y'])

In [0]:
#sub['Id'] = I

In [0]:
sub

y
0      0.201330
1      0.037763
2      0.037009
3      0.000798
4      0.009829
...         ...
84995  0.000002
84996  0.000002
84997  0.000001
84998  0.000002
84999  0.000076

[85000 rows x 1 columns]

In [0]:
CSV=sub.to_csv('sub1.csv')